### ISSUE TITLE
Adjust xDai Chain logo to Gnosis Chain logo in "Our Partners"

### ISSUE THREAD

**Issue by skyminert** [KeenanLukeOM/DXdaoLandingPage#14]
We are using old xDai Chain logo.  Update to Gnosis Chain logo.

![image](https://user-images.githubusercontent.com/57817726/167773656-cf96cbda-ec1a-4a11-9df8-7eac64af11c5.png)

Gnosis Chain logo here: https://www.xdaichain.com/media/media-kit

**Comment by KeenanLukeOM** [comment]
Closed by #15
